spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_recipe_dev
    username: sfg_dev_user
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    # Uncomment the lines below to generate SQL that creates the database schema
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: sfg_database_create.sql
